version: '3.8'

services:
  app:
    build: .
    container_name: practice_app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=practice_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15.1-alpine
    container_name: practice_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: practice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - practice_postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: practice_pgweb
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/practice_db?sslmode=disable
    depends_on:
      - postgres

volumes:
  practice_postgres_data:
